# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  infraweb:
    image: infraweb
    build:
      context: .
      dockerfile: infra-web/Dockerfile
    ports:
      - 3000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  infraapi:
    image: infraapi
    build:
      context: .
      dockerfile: infra-api/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw